### ISSUE TITLE
Implicit requirement of valid `Item`s for formatting

### ISSUE THREAD

**Issue by drahnr** [dtolnay/prettyplease#19]
Currently the implementation requires a valid `syn::File` rather than an arbitrary tokenstream (well, an _almost_ correct one), already stated in #5 and #6 .

To bridge this gap the knee jerk reaction is:

```rust
let f = syn::parse2::<syn::File>(tokenstream)?; 
prettyplease::unparse(f);
```
but it has a practical issue. Unlike `rustfmt`, it doesn't try it's best to fix the content, which is a hindrance when developing a proc-macro. But when would one be interested in the generated code beyond development or debugging? I personally would see it as a viable usecase for `prettyplease` :)

Context: https://github.com/drahnr/expander uses the host's `rustfmt` 

Note that I am sorry to open the can of #5 and #6 again, I think this adds some more insight why a `Tokenstream` based API might be useful.

Thank you for your continued, awesome work! :heart:

**Comment by dtolnay** [comment]
I think valid Items is a reasonable requirement for formatting using this crate.
