### ISSUE TITLE
Trailing comma in tuple removed

### ISSUE THREAD

**Issue by 6xzo** [dtolnay/prettyplease#3]
Hi,

I am generating routes for warp, with function return types that look like this:

```
warp::filters::BoxedFilter<(impl Reply,)>
```

You can see the same in a [warp example](https://docs.rs/warp/latest/warp/filters/struct.BoxedFilter.html).

`prettyplease` removes the trailing comma inside the tuple and the code does not compile.

Is this inside or outside the 95% that you wish to cover?

**Comment by dtolnay** [comment]
Should be fixed in 0.1.1.

**Comment by 6xzo** [comment]
I tested this in my case and it works. Thank you.
