### ISSUE TITLE
Fails to format multiline doc comments containing comment end characters

### ISSUE THREAD

**Issue by mohe2015** [dtolnay/prettyplease#31]
Hi,

I tried using this for generating code based on some schema and the comments in that schema contain file glob patterns that contain the comment end characters `*/`. It seems like this library fails to handle them although it works when just using the code inside a proc macro. See https://github.com/mohe2015/prettyplease-bug/blob/main/src/main.rs for a reproducible example.

Kind regards
Moritz

**Comment by dtolnay** [comment]
Thanks &mdash; Fixed in 0.1.21.
