### ISSUE TITLE
Support for let-else

### ISSUE THREAD

**Issue by khionu** [dtolnay/prettyplease#34]
Hi, fantastic crate, much appreciated!

I was hoping support for let-else could be added? Currently panics:
```
thread 'main' panicked at 'not implemented: Expr::Verbatim `let Ok (_) = conn . exec (mig , []) else { color_eyre :: eyre :: bail ! ("migration {i}_{name} failed") ; }`', /home/khionu/.cargo/registry/src/github.com-1ecc6299db9ec823/prettyplease-0.1.23/src/expr.rs:692:13
```

**Comment by GilShoshan94** [comment]
I see works to parse `let-else` has been done in `syn` https://github.com/dtolnay/syn/pull/1231 and https://github.com/dtolnay/syn/pull/1057.

And indeed the parsing `syn::parse_file` works, it panicked only in the `prettyplease::unparse` call.
Looking at the error stack, it seems that the `let-else` is treated as a `Expr::Verbatim` in the match `prettyplease\src\expr.rs` (line 58).

I tried the feature = "verbatim", but it didn't help to deal with the `let-else`...

looking more into the `syn` crate, the [syn](https://docs.rs/syn/latest/syn/index.html)::[ExprLet](https://docs.rs/syn/latest/syn/struct.ExprLet.html#) can get another expr after the Eq token `=`, and [syn](https://docs.rs/syn/latest/syn/index.html)::[Expr](https://docs.rs/syn/latest/syn/enum.Expr.html#) with all its variants has not a this special case "`patern` `else` `block`". 

@dtolnay what is your approach to solve this ?
1. Should we try to improve `syn` to not parse `let-else` as a verbatim ?
2. Should we have a special case in prettyplease to handle a verbatim `let-else` ?

It seems like 1. is desirable but very hard.

Of course I might (probably) be missing something.

**Comment by khionu** [comment]
:purple_heart: Thank you very much
