### ISSUE TITLE
Support for `syn::custom_keyword`? 

### ISSUE THREAD

**Issue by kennykerr** [dtolnay/prettyplease#35]
Maybe I missed it, but I don't see an obvious way to support custom keywords since the crate's only public function expects a `syn::File`? 

Any chance this is possible? Many thanks.

**Comment by dtolnay** [comment]
I don't understand what this means. Could you clarify?

**Comment by kennykerr** [comment]
I have my own custom Rust-like syntax that depends on `syn::custom_keyword` for parsing with the `syn` crate and I'd like to offer the ability to format these Rust-like source files with `prettyplease` since its mostly just Rust with the addition of a handful of custom keywords. 

Right now, I'm having to escape the custom keywords, call `rustfmt`, and then unescape the result. I figure `prettyplease` would be less brittle if it supported custom keywords.

**Comment by dtolnay** [comment]
Got it. I'd prefer to keep this crate just for formatting syn::File.
