### ISSUE TITLE
Feature request: non-FS-based API, ie unparse `syn` types to `String`

### ISSUE THREAD

**Issue by nathan-at-least** [dtolnay/prettyplease#46]
# What I'd like

An API that operates in memory with no fs or other IO:
```
pub fn unparse_tokens(ast: proc_macro2::TokenStream) -> String;
```

# Motivation

I'm hunting for a pretty-printing library for use in proc-macro2-based unittests.

These unittests want to assert that my procmacro transforms code into the expected value (at the `proc_macro2::TokenStream` abstraction, not whitespace sensitive). I do this with `assert_eq!(expected.to_string(), output.to_string)`, the heart of which looks like this:

```
use proc_macro2::TokenStream;

fn assert_tokens_eq(a: TokenStream, b: TokenStream) {
    let atext = a.to_string();
    let btext = b.to_string();
    assert_eq!(atext, btext);
}
```

So far, so good. But if there are failing tests, I get an eye-crossing comparison of two long unpretty rust source strings.

With the proposed API available, I'd modify my test helper to:

```
use proc_macro2::TokenStream;
use prettyplease::unparse_tokens;

fn assert_tokens_eq(expected: TokenStream, actual: TokenStream) {
    let expected = unparse_tokens(expected);
    let actual = unparse_tokens(actual);
    assert_eq!(
        &expected,
        &actual,
        "Source not equivalent:\n\n=== expected ===\n{expected}\n\n=== actual ===\b{actual}\n\n",
    );
}
```

The ideal is on test failures I can review the differences in a manner that feels natural for rust programmers.

**Comment by dtolnay** [comment]
The current API is already non-FS-based.

**Comment by nathan-at-least** [comment]
Yep! Apologies. I just came to close this issue myself. When viewing https://docs.rs/prettyplease/latest/prettyplease/fn.unparse.html which displays only the final component of type paths, I assumed `File` meant `std::fs::File`.
