### ISSUE TITLE
marco_rules with parenthesizes 

### ISSUE THREAD

**Issue by UtherII** [dtolnay/prettyplease#48]
-- ❤️  --
macro_rules used with parenthesizes at the top level are prettified with braces, but the semicolon at the end is kept unchanged. The problem is the semicolon is required behind macro_rules with parenthesizes, but it causes an error behind braces. 

    macro_rules! x (
          () => {}  
    );

is prettified to 

    macro_rules! x {
          () => {}  
    };

I guess you should either keep parenthesizes or remove the final semicolon when switching to braces (but I'm not sure they won't be other side effect).

**Comment by dtolnay** [comment]
Fixed in 0.2.6.
