### ISSUE TITLE
Support for `syn::Expr`?

### ISSUE THREAD

**Issue by jkelleyrtp** [dtolnay/prettyplease#5]
I'm building an autoformatter for a macro and would like to support autoformatting arbitrary rust expressions inside said macro.

Prettyplease is amazing for this :)

Unfortunately, the only API accessible for printing is through the `syn::File` type - which means I have to manually wrap each expression with `fn main() { #tokens }` and then trim off the beginning/end.

I saw the `Printer` type - but it's not exposed to just print the `Expr` type.

Is this is something you'd be interested in supporting? Any gudance on how to add it?

**Comment by dtolnay** [comment]
I would prefer not to add that into this crate.
