### ISSUE TITLE
Preserving non-doc comments

### ISSUE THREAD

**Issue by jdisanti** [dtolnay/prettyplease#50]
I'm evaluating using prettyplease in the [awslabs/smithy-rs](https://github.com/awslabs/smithy-rs) code generator since rustfmt has started failing for a lot of our generated code, but the removal of non-doc comments when formatting will effectively kill our debug mode where we add comments to each line indicating where in our code generator that line was generated from.

I understand these comments are considered whitespace in `syn`, so it may be a considerable amount of work to preserve them. Is preserving non-doc comments something you're interested in supporting in prettyplease, and if so, is it something we could potentially contribute?

**Comment by dtolnay** [comment]
It is not something I am interested in supporting.
