### ISSUE TITLE
Using prettyplease on non-file syn syntax tree data structures

### ISSUE THREAD

**Issue by naturecodevoid** [dtolnay/prettyplease#57]
Hi,

Currently there is no API to use prettyplease on things such as expressions and other syntax tree data structures that syn provides, such as an `Item`.

Would it be possible for this to be implemented in the future? To avoid making a function for every data structure syn provides, it may be possible to simply provide functions for enums such as `Expr` and `Item`.

For now, I'll just put the expression I need to format in a function and parse that as a file, but this approach is inefficient as it requires reparsing the already parsed expression.

**Comment by dtolnay** [comment]
This is a duplicate of #5.

**Comment by naturecodevoid** [comment]
Got it, thanks!

Is there any reason you don't want to add it, even behind a feature gate or something?
