### ISSUE TITLE
Directly format a TokenStream

### ISSUE THREAD

**Issue by lovesegfault** [dtolnay/prettyplease#6]
It'd be nice if a utility method were provided that takes a `TokenStream` and outputs a formatted String.

**Comment by dtolnay** [comment]
I would prefer not to add this.

**Comment by lovesegfault** [comment]
Got it, any specific reason why?

Currently I'm working around this like so, not sure if there's an easier way
```Rust
let ts = proc_macro2::TokenStream::new();
let f: syn::File = syn::parse2(ts)?;
let pretty = prettyplease::unparse(&f);
```
