### ISSUE TITLE
Support for alternative indentation styles

### ISSUE THREAD

**Issue by Enduriel** [dtolnay/prettyplease#75]
Would you be interested in supporting alternative indentation styles in this crate? Specifically tabs and potentially alternative width spaces? Trying to understand if this is in scope for the project since it's being used in downstream formatting crates which are not able to fully support tabs or alternate width spaces due to this feature being unsupported.

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate.

The algorithm would be compatible with hard tab or alternate number of spaces, so someone should feel free to maintain a fork with that functionality.
