### ISSUE TITLE
`Item::Verbatim` support

### ISSUE THREAD

**Issue by adetaylor** [dtolnay/prettyplease#8]
Would you be open to accepting a PR to add support for `Item::Verbatim` by using `quote::ToTokens::to_tokens().to_string()` or thereabouts?

If so, would you prefer this to be added under an optional feature?

**Comment by dtolnay** [comment]
`quote::ToTokens::to_tokens().to_string()` is not pretty formatting. I would be open to a PR that nicely formats `Verbatim` behind an opt-in feature.

**Comment by adetaylor** [comment]
Thanks. At this point it's not a sufficiently high priority for me to come up with an algorithm to _nicely_ format `Verbatim` (I guess I'd do something like whatever `rustfmt` does) so for now I'll just close this.
