### ISSUE TITLE
Make `Printer` and related non-rust methods public behind a feature flag

### ISSUE THREAD

**Issue by tgross35** [dtolnay/prettyplease#86]
I have a usecase where am using `prettyprint` for printing Rust syntax, but I also need to pretty print some simple near-rust or non-rust syntax. It would be convenient to reuse this crate's `Printer` logic with the methods in `algorithm` and `convenience`. Would you be open to making this language-agnostic portion of the crate public?

(Understood if this is out of scope, figured it's worth an ask before either duplicating the implementation or switching to something more heavyweight).

**Comment by dtolnay** [comment]
I think that would be out of scope for this crate. But the code is appropriately licensed to be used elsewhere.
